make: part1.c part2.c part3.c part4.c part5.c
	gcc -std=c11 -lpthreads -o part1.exe part1.c
	gcc -std=c11 -lpthreads -o part2.exe part2.c
	gcc -std=c11 -lpthreads -o part3.exe part3.c
	gcc -std=c11 -lpthreads -o part4.exe part4.c
	gcc -std=c11 -lpthreads -o part5.exe part5.c
	gcc -std=c11 -lpthreads -o server part5.c
